sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t makander/docker-react -f Dockerfile.dev .
  
script:
  - docker run -e CI=true makander/docker-react npm run test -- --coverage